const SET_COURSES = 'SET_COURSES';
const UPDATE_COURSE_BY_ID = 'UPDATE_COURSE_BY_ID';
const DELETE_COURSE_BY_ID = 'DELETE_COURSE_BY_ID';

export { SET_COURSES, UPDATE_COURSE_BY_ID, DELETE_COURSE_BY_ID };

export default SET_COURSES;
