const SET_SUBJECTS = 'SET_SUBJECTS';
const UPDATE_SUBJECT_BY_ID = 'UPDATE_SUBJECT_BY_ID';
const DELETE_SUBJECT_BY_ID = 'DELETE_SUBJECT_BY_ID';

export { SET_SUBJECTS, UPDATE_SUBJECT_BY_ID, DELETE_SUBJECT_BY_ID };

export default SET_SUBJECTS;
