const SET_TEACHING_ASSISTANTS = 'SET_TEACHING_ASSISTANTS';
const UPDATE_TEACHING_ASSISTANTS_BY_ID = 'UPDATE_TEACHING_ASSISTANTS_BY_ID';
const DELETE_TEACHING_ASSISTANTS_BY_ID = 'DELETE_TEACHING_ASSISTANTS_BY_ID';
const BULK_DELETE_TEACHING_ASSISTANTS_BY_IDS = 'BULK_DELETE_TEACHING_ASSISTANTS_BY_IDS';

export { SET_TEACHING_ASSISTANTS, UPDATE_TEACHING_ASSISTANTS_BY_ID, DELETE_TEACHING_ASSISTANTS_BY_ID, BULK_DELETE_TEACHING_ASSISTANTS_BY_IDS };

export default SET_TEACHING_ASSISTANTS;
