const SET_TEACHERS = 'SET_TEACHERS';
const UPDATE_TEACHER_BY_ID = 'UPDATE_TEACHER_BY_ID';
const DELETE_TEACHER_BY_ID = 'DELETE_TEACHER_BY_ID';

export { SET_TEACHERS, UPDATE_TEACHER_BY_ID, DELETE_TEACHER_BY_ID };

export default SET_TEACHERS;
