const SET_ROLES = "SET_ROLES";
const UPDATE_ROLE_BY_ID = "UPDATE_ROLE_BY_ID";
const DELETE_ROLE_BY_ID = "DELETE_ROLE_BY_ID";
const BULK_DELETE_ROLES_BY_IDS = "BULK_DELETE_ROLES_BY_IDS";

export {
  SET_ROLES,
  UPDATE_ROLE_BY_ID,
  DELETE_ROLE_BY_ID,
  BULK_DELETE_ROLES_BY_IDS
};

export default SET_ROLES;
