const SET_TESTS = 'SET_TESTS';
const SET_TAKERS = 'SET_TAKERS';
const UPDATE_TEST_BY_ID = 'UPDATE_TEST_BY_ID';
const UPDATE_TAKER_BY_ID = 'UPDATE_TAKER_BY_ID';
const DELETE_TEST_BY_ID = 'DELETE_TEST_BY_ID';
const DELETE_TAKER_BY_ID = 'DELETE_TAKER_BY_ID';
const BULK_DELETE_TESTS_BY_IDS = 'BULK_DELETE_TESTS_BY_IDS';
const BULK_DELETE_TAKERS_BY_IDS = 'BULK_DELETE_TAKERS_BY_IDS';

export {
  SET_TESTS,
  SET_TAKERS,
  UPDATE_TEST_BY_ID,
  UPDATE_TAKER_BY_ID,
  DELETE_TEST_BY_ID,
  DELETE_TAKER_BY_ID,
  BULK_DELETE_TESTS_BY_IDS,
  BULK_DELETE_TAKERS_BY_IDS
};

export default SET_TESTS;
