const SET_FAULTS = 'SET_FAULTS';
const UPDATE_FAULT_BY_ID = 'UPDATE_FAULT_BY_ID';
const DELETE_FAULT_BY_ID = 'DELETE_FAULT_BY_ID';
const BULK_DELETE_FAULTS_BY_IDS = 'BULK_DELETE_FAULTS_BY_IDS';

export {
  SET_FAULTS,
  UPDATE_FAULT_BY_ID,
  DELETE_FAULT_BY_ID,
  BULK_DELETE_FAULTS_BY_IDS
};

export default SET_FAULTS;
