const SET_PHASE = 'SET_PHASE';
const UPDATE_PHASE_BY_ID = 'UPDATE_PHASE_BY_ID';
const DELETE_PHASE_BY_ID = 'DELETE_PHASE_BY_ID';
const REMOVE_PHASE_TEACHER_BY_ID = 'REMOVE_PHASE_TEACHER_BY_ID';
const REMOVE_PHASE_ASSISTANT_BY_ID = 'REMOVE_PHASE_ASSISTANT_BY_ID';
const REMOVE_PHASE_STUDENT_BY_ID = 'REMOVE_PHASE_STUDENT_BY_ID';

export {
  SET_PHASE,
  UPDATE_PHASE_BY_ID,
  DELETE_PHASE_BY_ID,
  REMOVE_PHASE_TEACHER_BY_ID,
  REMOVE_PHASE_ASSISTANT_BY_ID,
  REMOVE_PHASE_STUDENT_BY_ID
};

export default SET_PHASE;
