const SET_ROOMS = 'SET_ROOMS';
const UPDATE_ROOM_BY_ID = 'UPDATE_ROOM_BY_ID';
const DELETE_ROOM_BY_ID = 'DELETE_ROOM_BY_ID';

export { SET_ROOMS, UPDATE_ROOM_BY_ID, DELETE_ROOM_BY_ID };

export default SET_ROOMS;
