const SET_SESSION = 'SET_SESSION';
const UPDATE_SESSION_BY_ID = 'UPDATE_SESSION_BY_ID';
const DELETE_SESSION_BY_ID = 'DELETE_SESSION_BY_ID';
const BULK_DELETE_SESSION_BY_IDS = 'BULK_DELETE_SESSION_BY_IDS';
const UPDATE_SUMMARY_BY_ID = 'UPDATE_SUMMARY_BY_ID';

export {
  SET_SESSION,
  UPDATE_SESSION_BY_ID,
  DELETE_SESSION_BY_ID,
  BULK_DELETE_SESSION_BY_IDS,
  UPDATE_SUMMARY_BY_ID
};

export default SET_SESSION;
