const SET_STUDENTS = 'SET_STUDENTS';
const UPDATE_STUDENT_BY_ID = 'UPDATE_STUDENT_BY_ID';
const DELETE_STUDENT_BY_ID = 'DELETE_STUDENT_BY_ID';
const BULK_DELETE_STUDENTS_BY_IDS = 'BULK_DELETE_STUDENTS_BY_IDS';

export { SET_STUDENTS, UPDATE_STUDENT_BY_ID, DELETE_STUDENT_BY_ID, BULK_DELETE_STUDENTS_BY_IDS };

export default SET_STUDENTS;
