const SET_CLASSES = 'SET_CLASSES';
const UPDATE_CLASS_BY_ID = 'UPDATE_CLASS_BY_ID';
const ADD_STUDY_PHASE_TO_CLASS = 'ADD_STUDY_PHASE_TO_CLASS';

export { SET_CLASSES, UPDATE_CLASS_BY_ID, ADD_STUDY_PHASE_TO_CLASS };

export default SET_CLASSES;
