const SET_REGISTRATION_CODES = 'SET_REGISTRATION_CODES';
const DELETE_REGISTRATION_CODE_BY_ID = 'DELETE_REGISTRATION_CODE_BY_ID';
const BULK_DELETE_REGISTRATION_CODES_BY_IDS = 'BULK_DELETE_REGISTRATION_CODES_BY_IDS';

export { SET_REGISTRATION_CODES, DELETE_REGISTRATION_CODE_BY_ID, BULK_DELETE_REGISTRATION_CODES_BY_IDS };

export default SET_REGISTRATION_CODES;
