const SET_STATUS = 'SET_STATUS';
const UPDATE_STATUS_BY_ID = 'UPDATE_STATUS_BY_ID';
const DELETE_STATUS_BY_ID = 'DELETE_STATUS_BY_ID';
const BULK_DELETE_STATUS_BY_IDS = 'BULK_DELETE_STATUS_BY_IDS';

export { SET_STATUS, UPDATE_STATUS_BY_ID, DELETE_STATUS_BY_ID, BULK_DELETE_STATUS_BY_IDS };

export default SET_STATUS;
